version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12.0
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-155-35-88.eu-west-1.compute.amazonaws.com
            port: '5432'
            database: otqzdhxmhdmupf
            ssl: true
            user: otqzdhxmhdmupf
            password: 7cccbaea23de51d279ea757372094cedc1fa8b2f9f6ccc22b195d01eb4ca62a4
            migrations: true